version: '3.0'

services:

  jupyter:
    build:
      context: notebook-docker
      dockerfile: Dockerfile
    image: jyp-notebook_kafka:v2
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./notebook-docker:/home/jovyan/work/build
      - ./src:/home/jovyan/work/src
    ports:
      - 8888:8888
    links:
      - kafka
      - zookeeper
      - db

  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - 2181
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      KAFKA_CREATE_TOPICS: "clickstream:2:1,bookmarks:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: always

  db:
    image: postgres:12
    restart: always
    env_file:
      - ./src/database.env
    volumes:
      - ./scripts/init:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data: